### ISSUE TITLE
Optional svgo parameter

### ISSUE THREAD

**Issue by marinatells** [darkartur/svgson-loader#1]
We use our own config for svgo optimisations, default config messes them up.

**Comment by elrumordelaluz** [comment]
Are you using [`svgoConfig`](https://github.com/elrumordelaluz/svgson/blob/master/lib/svgson.js#L74) option?

**Comment by darkartur** [comment]
Solved in PR #2

**Comment by elrumordelaluz** [comment]
Since version `3.x` svgson won't bundle `svgo` anymore because from `svgo@^1` supports _Promises_ pretty well. Keep in mind that upgrading into `svgson@^3` means a [big weight drop](https://bundlephobia.com/result?p=svgson@3.0.0) (from ~111kb into ~9kb). Let me know if there are any question.
